version: 2.1

jobs:
  run-ui-tests:
    machine:
      image: windows-server-2019-vs2019:stable
    steps:
      - checkout
      - run:
          name: Install NVM
          command: |
            Invoke-WebRequest -Uri https://raw.githubusercontent.com/coreybutler/nvm-windows/v1.1.7/install.cmd -OutFile install-nvm.cmd
            ./install-nvm.cmd
            nvm install 20
            nvm use 20
      - run:
          name: Install Dependencies
          command: |
            cd siemens-SDET\UI_tests
            npm install
      - run:
          name: Run UI Tests
          command: |
            cd siemens-SDET\UI_tests
            npx nightwatch -e chrome
      - store_artifacts:
          path: siemens-SDET\UI_tests\tests_output\nightwatch-html-report\index.html
          destination: ui-test-report

  run-api-tests:
    machine:
      image: windows-server-2019-vs2019:stable
    steps:
      - checkout
      - run:
          name: Install NVM
          command: |
            Invoke-WebRequest -Uri https://raw.githubusercontent.com/coreybutler/nvm-windows/v1.1.7/install.cmd -OutFile install-nvm.cmd
            ./install-nvm.cmd
            nvm install 11
            nvm use 11
      - run:
          name: Install Dependencies
          command: |
            cd siemens-SDET\mock-user-auth
            npm install
      - run:
          name: Start Server
          command: |
            Start-Process cmd -ArgumentList '/c npm run dev' -NoNewWindow
      - run:
          name: Run API Tests
          command: |
            cd siemens-SDET\mock-user-auth
            $env:NODE_ENV="test"
            .\node_modules\.bin\mocha --require @babel/register --require babel-polyfill --reporter mocha-multi-reporters --reporter-options configFile=reporter-config.json .\test\**\*.spec.js
      - store_artifacts:
          path: siemens-SDET\mock-user-auth\reports\mochawesome.html
          destination: api-test-report

workflows:
  version: 2
  test:
    jobs:
      - run-ui-tests
      - run-api-tests:
          requires:
            - run-ui-tests
