version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

executors:
  windows-executor:
    machine:
      image: windows-server-2019-vs2019:2024.05.1
      resource_class: windows.medium

jobs:
  run-ui-tests:
    executor: windows-executor
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install

      - run:
          name: Install NVM
          shell: powershell.exe
          command: |
            Invoke-WebRequest -Uri https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-setup.exe -OutFile nvm-setup.exe
            Start-Process .\nvm-setup.exe -Wait
            nvm install 20
            nvm use 20
      - run:
          name: Install Dependencies
          shell: powershell.exe
          command: |
            ls
            cd UI_tests
            npm install
      - run:
          name: Run UI Tests
          shell: powershell.exe
          command: |
            ls
            cd UI_tests
            npx nightwatch -e chrome


  run-api-tests:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: Install NVM
          shell: powershell.exe
          command: |
            Invoke-WebRequest -Uri https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-setup.exe -OutFile nvm-setup.exe
            Start-Process .\nvm-setup.exe -Wait
            nvm install 11
            nvm use 11
      - run:
          name: Install Dependencies
          shell: powershell.exe
          command: |
            cd mock-user-auth
            npm install
      - run:
          name: Start Server
          background: true
          shell: powershell.exe
          command: |
            cd mock-user-auth
            npm run dev
      - run:
          name: Run API Tests
          shell: powershell.exe
          command: |
            cd mock-user-auth
            $env:NODE_ENV="test"
            .\node_modules\.bin\mocha --require @babel/register --require babel-polyfill --reporter mocha-multi-reporters --reporter-options configFile=reporter-config.json .\test\**\*.spec.js


workflows:
  version: 2
  test:
    jobs:
      - run-ui-tests
      - run-api-tests:
          requires:
            - run-ui-tests
