version: 2.1

executors:
  windows-executor:
    machine:
      image: windows-server-2019-vs2019:2024.05.1
      resource_class: windows.medium

jobs:
  
  run-api-tests:
    executor: windows-executor
    steps:
      - run:
          name: Clone Repository
          shell: powershell.exe
          command: |
            git clone https://github.com/Heba2h/siemens-SDET C:\Users\circleci\project\siemens-SDET
      - run:
          name: Install NVM
          shell: powershell.exe
          command: |
            Invoke-WebRequest -Uri https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-setup.exe -OutFile nvm-setup.exe
            Start-Process .\nvm-setup.exe -Wait
            $env:PATH += ";C:\Program Files\nodejs"
            nvm install 11
            nvm use 11
      - run:
          name: Install Dependencies
          shell: powershell.exe
          command: |
            cd C:\Users\circleci\project\siemens-SDET\mock-user-auth
            npm install
      - run:
          name: Start Server
          shell: powershell.exe
          background: true
          command: |
            cd C:\Users\circleci\project\siemens-SDET\mock-user-auth
            npm run dev
      - run:
          name: Run API Tests
          shell: powershell.exe
          command: |
            cd C:\Users\circleci\project\siemens-SDET\mock-user-auth
            $env:NODE_ENV="test"
            .\node_modules\.bin\mocha --require @babel/register --require babel-polyfill --reporter mocha-multi-reporters --reporter-options configFile=reporter-config.json .\test\**\*.spec.js
      - store_artifacts:
          path: C:\Users\circleci\project\siemens-SDET\mock-user-auth\reports\mochawesome.html
          destination: api-test-report

workflows:
  version: 2
  test:
    jobs:
      - run-api-tests
