version: 2.1

executors:
  windows-executor:
    machine:
      image: windows-server-2019-vs2019:2024.05.1
      resource_class: windows.medium

jobs:
  run-ui-tests:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: Install NVM
          shell: powershell.exe
          command: |
            Invoke-WebRequest -Uri https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-setup.exe -OutFile nvm-setup.exe
            Start-Process .\nvm-setup.exe -Wait
            nvm install 20
            nvm use 20
      - run:
          name: Install Dependencies
          command: |
            cd siemens-SDET\UI_tests
            npm install
      - run:
          name: Run UI Tests
          command: |
            cd siemens-SDET\UI_tests
            npx nightwatch -e chrome
      - store_artifacts:
          path: siemens-SDET\UI_tests\tests_output\nightwatch-html-report\index.html
          destination: ui-test-report

  run-api-tests:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: Install NVM
          shell: powershell.exe
          command: |
            Invoke-WebRequest -Uri https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-setup.exe -OutFile nvm-setup.exe
            Start-Process .\nvm-setup.exe -Wait
            nvm install 11
            nvm use 11
      - run:
          name: Install Dependencies
          command: |
            cd siemens-SDET\mock-user-auth
            npm install
      - run:
          name: Start Server
          background: true
          command: |
            cd siemens-SDET\mock-user-auth
            npm run dev
      - run:
          name: Run API Tests
          shell: powershell.exe
          command: |
            cd siemens-SDET\mock-user-auth
            $env:NODE_ENV="test"
            .\node_modules\.bin\mocha --require @babel/register --require babel-polyfill --reporter mocha-multi-reporters --reporter-options configFile=reporter-config.json .\test\**\*.spec.js
      - store_artifacts:
          path: siemens-SDET\mock-user-auth\reports\mochawesome.html
          destination: api-test-report

workflows:
  version: 2
  test:
    jobs:
      - run-ui-tests
      - run-api-tests:
          requires:
            - run-ui-tests
