version: 2.1

jobs:
  run-ui-tests:
    docker:
      - image: node:20
    steps:
      - checkout
      - run:
          name: Install NVM
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 20
            nvm use 20
      - run:
          name: Install Dependencies
          command: |
            cd siemens-SDET/UI_tests/
            npm install
      - run:
          name: Run UI Tests
          command: |
            cd siemens-SDET/UI_tests/
            npx nightwatch -e chrome
      - store_artifacts:
          path: siemens-SDET/UI_tests/tests_output/nightwatch-html-report/index.html
          destination: ui-test-report

  run-api-tests:
    docker:
      - image: node:11
    steps:
      - checkout
      - run:
          name: Install NVM
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 11
            nvm use 11
      - run:
          name: Install Dependencies
          command: |
            cd siemens-SDET/mock-user-auth/
            npm install
      - run:
          name: Start Server
          command: |
            cd siemens-SDET/mock-user-auth/
            npm run dev &
      - run:
          name: Run API Tests
          command: |
            cd siemens-SDET/mock-user-auth/
            export NODE_ENV="test"
            ./node_modules/.bin/mocha --require @babel/register --require babel-polyfill --reporter mocha-multi-reporters --reporter-options configFile=reporter-config.json ./test/**/*.spec.js
      - store_artifacts:
          path: siemens-SDET/mock-user-auth/reports/mochawesome.html
          destination: api-test-report

workflows:
  version: 2
  test:
    jobs:
      - run-ui-tests
      - run-api-tests:
          requires:
            - run-ui-tests
