version: 2.1

executors:
  windows-executor:
    machine:
      image: windows-server-2019-vs2019:2024.05.1
      resource_class: windows.medium

jobs:
  run-ui-tests:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: install Chrome
          shell: powershell.exe
          command: choco install googlechrome --ignore-checksums
          
      - run:
          name: Install NVM
          shell: powershell.exe
          command: |
            Invoke-WebRequest -Uri https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-setup.exe -OutFile nvm-setup.exe
            Start-Process .\nvm-setup.exe -Wait
            nvm install 20
            nvm use 20
      - run:
          name: Install Dependencies
          shell: powershell.exe
          command: |
            ls
            cd UI_tests
            npm install
      - run:
          name: Run UI Tests
          shell: powershell.exe
          command: |
            ls
            cd UI_tests
            npx nightwatch -e chrome

      - store_artifacts:
          path: C:\Users\circleci\project\UI_tests\tests_output\nightwatch-html-report\index.html
          destination: ui-test-report
          when: always 


  run-api-tests:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: Install NVM
          shell: powershell.exe
          command: |
            Invoke-WebRequest -Uri https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-setup.exe -OutFile nvm-setup.exe
            Start-Process .\nvm-setup.exe -Wait
            nvm install 11.15.0
            nvm use 11.15.0
      - run:
          name: Install Dependencies
          shell: powershell.exe
          command: |
            cd mock-user-auth
            npm install
      - run:
          name: Start Server
          background: true
          shell: powershell.exe
          command: |
            cd mock-user-auth
            npm run dev
      - run:
          name: Run API Tests
          shell: powershell.exe
          command: |
            cd mock-user-auth
            npm install mocha-junit-reporter
            $env:NODE_ENV="test"
            .\node_modules\.bin\mocha --require @babel/register --require babel-polyfill --reporter mocha-multi-reporters --reporter-options configFile=reporter-config.json .\test\**\*.spec.js
      - run:
          name: LS
          shell: powershell.exe
          command: 
            cd  C:\Users\circleci\project\mock-user-auth\reports
            ls 
          when: always

      - store_artifacts:
          path: C:\Users\circleci\project\mock-user-auth\reports\mochawesome.html
          destination: api-test-report
          when: always 

workflows:
  version: 2
  test:
    jobs:
      - run-ui-tests
      - run-api-tests
        
